### ISSUE TITLE
Issues with `.itm ~` style names on linux

### ISSUE THREAD

**Issue by waebbl** [RoxanneSHS/SandrahEET#4]
When installing the mod on linux I had several issues where names, for example `~acqxemer.itm ~` couldn't be copied, if after the filename there was a space before the `~` sign. It was only a problem, if there was a newline following. 
I downloaded the mod on May 29, but a quick check for the above example in master let's me assume, it's still present like this.
It could be, that Linux (or WeiDU for Linux) is more strict when it comes to name checking.

See this diff, of what I needed to change for the mod to install properly:

```
--- sandrahnpc/setup-sandrahnpc.tp2	2020-06-10 23:11:49.198079300 +0200
+++ archives/unpack/SandrahEET-master/SandrahNPC/Setup-SandrahNPC.tp2	2020-05-18 11:31:07.000000000 +0200
@@ -1813,23 +1813,23 @@
 END
 
 ACTION_IF NOT FILE_EXISTS_IN_GAME ~acqxemer.itm~ THEN BEGIN
-COPY ~SandrahNPC/ITM/acqxemer.itm~ ~override/acqxemer.itm~
+COPY ~SandrahNPC/ITM/acqxemer.itm~ ~override/acqxemer.itm ~
 END
 
 ACTION_IF NOT FILE_EXISTS_IN_GAME ~BGDEX16.SPL~ THEN BEGIN
-COPY ~SandrahNPC/Misc2/BGDEX16.SPL~ ~override/BGDEX16.SPL~
+COPY ~SandrahNPC/Misc2/BGDEX16.SPL~ ~override/BGDEX16.SPL ~
 END
 
 ACTION_IF NOT FILE_EXISTS_IN_GAME ~BGDEX17.SPL~ THEN BEGIN
-COPY ~SandrahNPC/Misc2/BGDEX17.SPL~ ~override/BGDEX17.SPL~
+COPY ~SandrahNPC/Misc2/BGDEX17.SPL~ ~override/BGDEX17.SPL ~
 END
 
 ACTION_IF NOT FILE_EXISTS_IN_GAME ~ACREVIS.BMP~ THEN BEGIN
-COPY ~SandrahNPC/Misc2/ACREVIS.BMP~ ~override/ACREVIS.BMP~
+COPY ~SandrahNPC/Misc2/ACREVIS.BMP~ ~override/ACREVIS.BMP ~
 END
 
 ACTION_IF NOT FILE_EXISTS_IN_GAME ~Gauthsu.cre~ THEN BEGIN
-COPY_EXISTING ~Behold01.cre~ ~override/Gauthsu.cre~
+COPY_EXISTING ~Behold01.cre~ ~override/Gauthsu.cre ~
      SAY NAME1 Gauth
      SAY NAME2 Gauth
      WRITE_BYTE 0x270 5 
@@ -1860,7 +1860,7 @@
 COMPILE ~SandrahNPC/Mods/acq40001.baf~
 EXTEND_TOP
 ~BG0900.BCS~ ~SandrahNPC/Mods/ac7900.baf~
-COPY ~SandrahNPC/Mods/acq40001.cre~ ~override/acq40001.cre~
+COPY ~SandrahNPC/Mods/acq40001.cre~ ~override/acq40001.cre ~
      SAY NAME1 Furlon
      SAY NAME2 Furlon
 END
@@ -2316,7 +2316,7 @@
 SAY BATTLE_CRY4 Craw
 
 COPY ~SandrahNPC/Kit/CVSLEEP.SPL~ ~override/CVSLEEP.SPL~
-COPY ~SandrahNPC/Kit/SanMove.eff~ ~override/SanMove.eff~
+COPY ~SandrahNPC/Kit/SanMove.eff~ ~override/SanMove.eff ~
 
 COPY ~SandrahNPC/Kit/CVMysAn.bam~ ~override/CVMysAn.bam~
 COPY ~SandrahNPC/Kit/CVMysAn2.bam~ ~override/CVMysAn2.bam~
@@ -5886,7 +5886,7 @@
 COPY_EXISTING ~ACqxzah1.cre~ ~override~ 
      WRITE_ASCII 0x34 ~Resach~
  END ELSE BEGIN
-COPY ~SandrahNPC/Mods/acqxzah1.cre~ ~override/acqxzah1.cre~
+COPY ~SandrahNPC/Mods/acqxzah1.cre~ ~override/acqxzah1.cre ~
      SAY NAME1 @403
      SAY NAME2 @403
 COMPILE ~SandrahNPC/Mods/acqxzah1.d~
@@ -5936,9 +5936,9 @@
 ~BG3300.BCS~ ~SandrahNPC/Mods/ar6700kelor.baf~
 EXTEND_TOP
 ~ar40pb.BCS~ ~SandrahNPC/Mods/ar40pbtalos.baf~
-COPY_EXISTING ~ntkeelor.cre~ ~override/ntkeelor.cre~
+COPY_EXISTING ~ntkeelor.cre~ ~override/ntkeelor.cre ~
      WRITE_ASCII 0x248 ~shout20~ #8
-COPY_EXISTING ~ntaschma.cre~ ~override/ntaschma.cre~
+COPY_EXISTING ~ntaschma.cre~ ~override/ntaschma.cre ~
      WRITE_ASCII 0x248 ~ntashma~ #8
      WRITE_ASCII 0x2cc ~ntashma~ #8
 EXTEND_TOP
```

**Comment by RoxanneSHS** [comment]
It seems that it is a linux issue since the "error" existed for several years already without anyone having trouble with it.
Anyway, I have updated the tp2 with your findings, after all it is an error even if windows seems to compensate it and just ignores the space after file extension.

**Comment by waebbl** [comment]
Thanks for updating the file.
The rest of the installation and the installation of the other two Sandrah mods went smooth.
There was an error showing up at some time during install, saying there was no shout ID 153 HELP_ME_GROUP153 in `shoudids.ids`, which was true after checking, but the installation continued. I didn't follow this issue, as the installation succeeded even with it.
Now there is an ID 153 in this file, but with a value of SUM_ATTACK_EVIL, where I have no clue which mod installed it.

**Comment by RoxanneSHS** [comment]
Nothing to worry about. 
The classification of "Error" in weidu installation is an often discussed issue. If the installation continues after such an error it is to be understood rather as "notification" addressed to the modder. In fact, you may find many of those for Sandrah as well as for other mods. 
Sandrah's scripts contain a lot of references to other mods without always checking if that particular mod is installed or not. A script with several hundred or even thousand lines of code can hardly be safely compiled during installation from dozens of if/if not condition. Thus, it is more stable to allow a few code lines that may never be used in game if the other mod is not there.
