### ISSUE TITLE
Letter to Sandrah can be used

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#49]
The letter was sent to the Sandrah when the party was just leaving Friendly Arm Inn.  This letter has an odd feature: it is a usable item, meaning that it can be deployed in the quick item slot and used just like a potion.  However, nothing happens after the letter is 'used' except for the letter itself being consumed.

Btw, I guess you intentionally used some archaic wording in this letter.  But considering that neither Sandrah nor her father ever used this kind of wording in conversations, it might be a little odd see it in a 'family letter'.  What's worse, such wording will make the letter pretty confusing for non-native English speakers.

**Comment by RoxanneSHS** [comment]
This is not specific for Sandrah's letter but for a lot of other letters you may get in the game as well. I noted that an item designated as scroll and as plot item works like that. If the flag "plot item" is removed, this is gone. 
I never observed this behaviour before - I am not sure if it was introduced to the game mechanics with patch 2.6. Original SoD items do not have it, so I assume that Beamdog changed something here.
