### ISSUE TITLE
Cannot give silver amulet/ring to Jenlig

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#51]
In Friendly arm inn Jenlig once asked for silver amulet/ring.  I tried to leave the item in the protagonist‘s inventory or her inventory but nothing happens even after I tried to talk to her.

Besides, it is a little surprising to see that Sandrah has no banter with Finch since they both come from Water deep.

**Comment by RoxanneSHS** [comment]
Keep the silver amulet. Some event will trigger in some of the overland outdoor areas.
There is crossmod between Sandrah and Finch (If you are not in a city and outdoors) - there is even an extra quest around Finch when you travel to Waterdeep at a later point (regardless of Finch is still in party or not).
