### ISSUE TITLE
Do I have to install any other mods before using Sandrah?

### ISSUE THREAD

**Issue by ahungry** [RoxanneSHS/SandrahEET#53]
Hi @RoxanneSHS - I don't have an account on your forums, but have one here, so I figured I'd ask where it's convenient for me :smiley: 

I noticed in the Sandrah installation page it mentioned having things like a Drizzt mod installed - on the http://eetcompatiblemods.baldursextendedworld.com/ page, I see this is something that must be installed prior to installing EET.

I've been playing with EET for the last month or so - would I be able to _just_ install Sandrah mod standalone, or does it have dependencies?

I use GNU/Linux, so I don't think I can use your installer (I've been hand installing everything with weinstall/weidu CLI program, and maintaining the order myself).

Edit:
Basing my question on this quote from here:
"
1.Install BGEE/SoD with (as a minimum) Drizzt Saga, BG1NPC Project - all other contents mods for BGEE/EET are compatible with Sandrah and will enhance the mod, a full list with all mods for which Sandrah contains crossmod content is in the readme
2.Install BG2EE plus EET 1.0 RC7 or higher using Weidu 2.40 (or better) with (as a minimum) DSotSC, Ascension, TDDz, NTotSC, Grey Clan, Siren's Call - all other contents mods for BG2EE/EET are compatible with Sandrah and will enhance the mod
   For NTotSC you may use https://github.com/R...hive/master.zip (tested, confirmed, both parts to be installed) or the Beta v2.0 (still under test) https://github.com/G...hive/master.zip"

What's the best way to download these?  I can interpolate most the abbreviations, but direct download links to 'weinstall'able GNU/Linux tp2 files would be best.

Source: http://www.shsforums.net/files/file/1154-sandrah-saga-for-eet/

**Comment by RoxanneSHS** [comment]
There are some dependencies for Sandrah and some of them require installation prior EET. There is a readme-pdf in the mod download and a section listing the required mods. It is save to install Sandrah very much at the end, but prior to worldmap-mod and EET_end.
As for mod links, you can probably best use the versions that install tool itself would download https://github.com/EE-Mod-Setup/EE-Mod-Setup/tree/master/App/Config/Global  if you look into any ini-file named for the mod, there is a Down= entry which is the link to use.

**Comment by ahungry** [comment]
Thank you!
