### ISSUE TITLE
ERROR Installing Sandrah ToB (EET) component 14

### ISSUE THREAD

**Issue by Lichtenshtein** [RoxanneSHS/SandrahEET#59]
Hi. I'm getting an error installing component 14 (Wheels of Prophecy 8.5 part).

```
[SandrahNPC/ToB/WheelsSanappend.d] loaded, 1602 bytes
SandrahNPC/ToB/WheelsSanappend.d copied to SandrahNPC/backup/14/WheelsSanappend.d, 1602 bytes
Copied [SandrahNPC/ToB/WheelsSanappend.d] to [SandrahNPC/ToB/WheelsSanappend.d]
Compiling 1 dialogue file ...
[SandrahNPC/TRA/russian/WheelsSanappend.TRA] has 27 translation strings

[SandrahNPC/ToB/WheelsSanappend.d] LEXER ERROR at line 5 column 1-23
Near Text: -
	invalid character [-]

[SandrahNPC/ToB/WheelsSanappend.d]  ERROR at line 5 column 1-23
Near Text: -
	Parsing.Parse_error
ERROR: parsing [SandrahNPC/ToB/WheelsSanappend.d]: Parsing.Parse_error
ERROR: compiling [SandrahNPC/ToB/WheelsSanappend.d]!
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Sandrah ToB (EET)], rolling back to previous state
```
 I don't find such character anywhere...

**Comment by RoxanneSHS** [comment]
This seems to be a format error in the file provided by our Russian translators just a few days ago.

To work around, copy the file WheelsSanappend.TRA from the Sandrah/NPC/Tra/English folder to the Russian folder.

By the way, it is an extremely bad idea to use the current version of Wheels of Prophesy in EET. I would advise to use the Ascension component Balthazar can be redeemed instead.

I will inform the translator to look into this problem.

**Comment by Lichtenshtein** [comment]
> It is possible that your system does not handle that correctly (chinese/russian keyboard?)

Maybe

> Delete everything except the first line and the last two lines.

Thanks. This won't mess up anything in game if i delete those lines, right? Sandrah-wheels component will work fine? Or maybe should i replace lines in balthadd.tra by myself before installing Sandrah component?

**Comment by RoxanneSHS** [comment]
Not sure about mess up because the current Wheels may be messing up things with or without. You will lose some dialogue and additional way to win Balthazar for your side but you may succeed without her if you do the right options in ToB.

If you find the lines needed in the Balth dialog you may of course replace them in the d-file with the current values before installation (you still need to disable those lines in tp2).
