### ISSUE TITLE
Incorrect talk lines in file "symiazsan.tra" file

### ISSUE THREAD

**Issue by abalabokhin** [RoxanneSHS/SandrahEET#6]
It seems that some lines in "symiazsan.tra" file are incorrect. Sandrah addresses Symiaz as a priestess, while he is a man and probably not a priest. 
I assume that some lines were copy-paster from "sallinithyl.tra" and were not fixed properly. Can you fix this "symiazsan.tra" file, please?
Thank you.

**Comment by RoxanneSHS** [comment]
I have changed priestess to Symiaz.
Thanks for the help.

**Comment by abalabokhin** [comment]
Thank you.
