### ISSUE TITLE
Problem with Sandrah mod

### ISSUE THREAD

**Issue by Antarmk1** [RoxanneSHS/SandrahEET#63]
I faced with some problems with sandrah mod.    (Main hero fem NG)
 
a) There isn`t any way to keep Sandrah in party without romance? She always force main hero to sleep with her, and i can decline that( 
b) Even if main hero in relationship with sandra she still sleep with strangers (Bjornin) and another companions (Garrik) 
That is as planned or bug? 
c) If Shar-Till in party Sandrah act like main hero and Shar-Till in romantic relationship. But Shar-Till can romance only with evil man with strg 11+, not with female with good aligement

**Comment by RoxanneSHS** [comment]
All of those are features not bugs.

**Comment by Antarmk1** [comment]
I still don`t understand how it can be feature.
Shar-Till romance requires only evil man with strg 11+. it impossible with Fen NG main hero.
And if Sandrah act like Shar-Till and Fen NG main hero in relationship it must be bug, or i missed something? 

Any way, is there solution to keep sandrah in party without being a part of her sweden family and s** interactions with companions and strangers? In dialogs i can`t find way to stop romance.  There are only one options in dialogs - send her away (but of course i don`t want lose her banters and reactions)

**Comment by Antarmk1** [comment]
> All of those are features not bugs.
sorry for bothering, but:

I still don`t understand how it can be feature.
Shar-Till romance requires only evil man with strg 11+. it impossible with Fen NG main hero.
And if Sandrah act like Shar-Till and Fen NG main hero in relationship it must be bug, or i missed something?

Any way, is there solution to keep sandrah in party without being a part of her sweden family and s** interactions with companions and strangers? In dialogs i cant find way to stop romance. There are only one options in dialogs - send her away (but of course i dont want lose her banters and reactions)

**Comment by RoxanneSHS** [comment]
Mods modify existing features, Sandrah + Shar-Teel in a party opens more possibilities for her and the player.
Sandrah allows the player to have any other romance they like without being exclusive - she takes the same right for herself - at least in the first half of the trilogy. Much later she is true to the player.

It is a matter of taste to allow that or not. It is a game, not real life.

**Comment by Antarmk1** [comment]
> It is a matter of taste to allow that or not. It is a game, not real life.

I don`t want to put restrictions on her. And force her to be loyal from start. I just want to keep her in party without any romantic relationship beetwin her and main hero. Just friends)  That is possible? 


> Mods modify existing features, Sandrah + Shar-Teel in a party opens more possibilities for her and the player. 

Does it mean that Sandrah mod removed restrictions from Shar-Till romance (only evil man with strg 11+) and made it available for any aligement and gender? And i must just wait some time before romantic conversations starts between Shar-Till and Fem NG main hero?

**Comment by RoxanneSHS** [comment]
No to both.

**Comment by Antarmk1** [comment]
> No to both.

Understood(

Thank you very much for your answers ).

Now I will start new game as CE/NE main hero, (like worshipper of slaanesh, if you know what i`m talking about)
And with that new main hero awkward & inappropriate situation should be acceptable. Like nude swimming + something else for entire party (Ajantis and Imoen was in party in that moment)        

That is definitely inappropriate for NG, but nice for CE/NE worshipper of slaanesh.
