### ISSUE TITLE
Issue with The Wheels of Prophecy crossmod

### ISSUE THREAD

**Issue by abalabokhin** [RoxanneSHS/SandrahEET#67]
Tried to install SandrahNPC with The Wheels of Prophecy mod, it failed to install with the error:

[SandrahNPC/ToB/WheelsSanappend.d] LEXER ERROR at line 5 column 1-23
Near Text: -
invalid character [-]

[SandrahNPC/ToB/WheelsSanappend.d] ERROR at line 5 column 1-23
Near Text: -
Parsing.Parse_error
ERROR: parsing [SandrahNPC/ToB/WheelsSanappend.d]: Parsing.Parse_error
ERROR: compiling [SandrahNPC/ToB/WheelsSanappend.d]!
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Sandrah ToB (EET)], rolling back to previous state
Will uninstall 117 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 14.
Uninstalled 117 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 14.
ERROR: Parsing.Parse_error

Can you fix it please?

**Comment by RoxanneSHS** [comment]
My best advice is NOT to use wheels mod anymore. It has never been properly updated after the big Ascension mod overhaul from last year. The Sandrah/Balthazar relation works fine with the new Ascension and without wheels.
I plan to remove the wheels crossmod but was not sure yet, still awaiting a possible update (may be possible there will be none.)

The error itself (Invalid character at line 5) makes no sense to me.

If you want to keep wheels nonetheless, just remove the tp2 part in Sandrah that tries to install the crossmod.

**Comment by abalabokhin** [comment]
Thank you. That helps a lot! As far as we understood, you are referring to this block in tp2 file:
ACTION_IF FILE_EXISTS_IN_GAME ~dw#melis.cre~ THEN BEGIN
OUTER_SET actual_207 = (STATE_WHICH_SAYS 123 IN ~wheels/tra/%s/balthadd.tra~ FROM ~balth~)
OUTER_SET actual_206 = (STATE_WHICH_SAYS 139 IN ~wheels/tra/%s/balthadd.tra~ FROM ~balth~)
COPY ~SandrahNPC/ToB/WheelsSanappend.d~ ~SandrahNPC/ToB/WheelsSanappend.d~
REPLACE_TEXTUALLY ~207~ ~%actual_207%~
REPLACE_TEXTUALLY ~206~ ~%actual_206%~
COMPILE ~SandrahNPC/ToB/WheelsSanappend.d~

It doesn't work, cause all the languages (but Chinese) are kept in "wheels/lang/" folder, not in "wheels/tra" folder. Moreover, all tra files are in ANSI encoding, and they are coded into utf-8 in folder "weidu_external". One replica number should also be altered...
Overall, after changing this two lines:
OUTER_SET actual_207 = (STATE_WHICH_SAYS 123 IN ~wheels/tra/%s/balthadd.tra~ FROM ~balth~)
OUTER_SET actual_206 = (STATE_WHICH_SAYS 139 IN ~wheels/tra/%s/balthadd.tra~ FROM ~balth~)
on:
OUTER_SET actual_207 = (STATE_WHICH_SAYS 140 IN ~weidu_external/lang/WHEELS/%s/balthadd.tra~ FROM ~balth~)
OUTER_SET actual_206 = (STATE_WHICH_SAYS 139 IN ~weidu_external/lang/WHEELS/%s/balthadd.tra~ FROM ~balth~)
SandrahNPC installed without any troubles. I am not sure it is bug free, though.

I can send you pull request with these changes if you like.

**Comment by RoxanneSHS** [comment]
Obviously there were changes made in Wheels since I last tested it myself. I admit that I did not follow these changes as they seem to be for an incomplete version.
However, if you provide an update pull request that you have tested, I will include it. I have no current build to test it myself.

**Comment by abalabokhin** [comment]
Ok, I sent pull request. Thank you.
