### ISSUE TITLE
Error with component SandrahNPC Extensions

### ISSUE THREAD

**Issue by Harted1** [RoxanneSHS/SandrahEET#71]
Hi!
I receive an error when installing component "SandrahNPC Extensions":

Install Component [SandrahNPC Extensions]?
[I]nstall, or [N]ot Install or [Q]uit? i

Installing [SandrahNPC Extensions] [v2.07]
Compiling 36 dialogue files ...
ERROR: internal label [101] appears 2 times in processed DLG [DOGHMA]
ERROR: postprocessing [DOGHMA]: Failure("cannot resolve label")
Stopping installation because of error.

ERROR Installing [SandrahNPC Extensions], rolling back to previous state
Will uninstall   0 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 11.
Uninstalled      0 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 11.
ERROR: Failure("cannot resolve label")
Please make a backup of the file: SETUP-SANDRAHNPC.DEBUG and look for support at: Roxanne - https://github.com/RoxanneSHS
Using Language [Russian (by arcanecoast.ru team)]

**Comment by RoxanneSHS** [comment]
Try this
Download https://www.dropbox.com/s/092vgah3sfahyeb/CVSandrJBG2.zip?dl=1
Extract the file to your BG2EE where you install the mods BG2EE/SandrahNPC/D
Try again.

**Comment by Harted1** [comment]
Yes, it works. The mod installed without errors. Thanks for the quick response!
