### ISSUE TITLE
Mulahey dies with no sheath

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#85]
I got a very strange problem related to Jen'lig's quest.

Mulahey (the orc at the bottom of Nashkel mine) should have Jen'lig's sheath, but if I kill him normally (the dialog options do not matter) the sheath mystically disappear.  However, by killing him using Ctrl + Y the sheath will be on the ground.

I have tried to solve the problem by myself but could not get any clue, so I guess I have to submit an issue here.  I have attached the weidu log as well as a quick save right before I killed Mulahey.

[WeiDU.log](https://github.com/RoxanneSHS/SandrahEET/files/13605952/WeiDU.log)
[WeiDU-BGEE.log](https://github.com/RoxanneSHS/SandrahEET/files/13605953/WeiDU-BGEE.log)
[000000001-(阿彼戴尔) Quick-Save.zip](https://github.com/RoxanneSHS/SandrahEET/files/13605964/000000001-.Quick-Save.zip)

**Comment by wuxiangjinxing** [comment]
After some more testing, the sheath did not disappear everytime I killed Mulahey normally, it disappeared about half of the times.

**Comment by wuxiangjinxing** [comment]
Okay I found out the problem: it's because Mulahey's pre-battle auto-cast of SPPR213.SPL (spiritual hammer).  Removing the corresponding lines from his default script solves the problem.

I still don't understand why spiritual hammer causes the sheath to disappear, though.

**Comment by RoxanneSHS** [comment]
Quick solution C:CreateItem("CVheath") after killing him and if sheath is missing...

If you want to find the issue, it needs local investigation on your game (maybe some incompatible mod). Find out which other mods affect Mulahey.bcs. (You can use https://www.dropbox.com/scl/fi/dkl50f6qton84zr9r9eyr/change-log.zip?rlkey=n8qrbyl5jwna68in4drknf1jv&dl=1 to anylyse).

**Comment by wuxiangjinxing** [comment]
Okay the reason is: the sheath is created on Mulahey as a magically created weapon, thus after he casted spiritual hammer, the sheath is overwritten.

I still have no idea why the sheath (which is a miscellaneous item) would be in his 'magically created weapon' slot, but could you help me check whether this item is created correctly in your game?  If it is a magically created weapon you would not be able to see it in his inventory after you use Ctrl + Q to forcefully recruit him and he will not be able to use any other weapons, but killing him with Ctrl + Y will drop the item on the ground.

**Comment by RoxanneSHS** [comment]
In the normal game, Mulahey does not cast the spell. Maybe some SCS component has assigned DW'Pr51.bcs (or a variation of it) to his class script slot. The sheath is not created in a specific slot but the script to do it uses CreateItem("CVheath",0,0,0). However, if his inventory is full already, it may not be created (I have no EET game currently to test it).
