### ISSUE TITLE
Finch can disappear

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#86]
If the Finch NPC mod is **NOT** installed, a non-joinable Finch will be provided by the Sandrah MOD.  However there is one problem: she is not a 'global' character (like how she is in the Finch NPC mod).

What happens is: after several in-game days (or maybe affected by in-game timers, not quite sure), she can be called by lord Deneir and disappear from the mortal Faerun world :)

**Comment by RoxanneSHS** [comment]
Did you look at the inn in Beregost? If she is not there, then check the big mansion in the north of Nashkel where she wants to set up her library.

**Comment by wuxiangjinxing** [comment]
I certainly know where she should be.  You use MoveBetweenArea to move her around.  But since she is not global, just like I told you she can disppear.


________________________________
发件人: Roxanne ***@***.***>
发送时间: 2023年12月17日 2:26
收件人: RoxanneSHS/SandrahEET ***@***.***>
抄送: wuxiangjinxing ***@***.***>; Author ***@***.***>
主题: Re: [RoxanneSHS/SandrahEET] Finch can disappear (Issue #86)


Did you look at the inn in Beregost? If she is not there, then check the big mansion in the north of Nashkel where she wants to set up her library.

―

**Comment by RoxanneSHS** [comment]
No need to worry. She is not really needed even for the quest named after her - she is just a plot excuse to carry the book for a while and bait the hunters.
