### ISSUE TITLE
Sandrah's parcel cannot be used by a cleric/ranger

### ISSUE THREAD

**Issue by wuxiangjinxing** [RoxanneSHS/SandrahEET#87]
I guess there are other items that might have the same problem :)

**Comment by RoxanneSHS** [comment]
An oversight...the class restrictions are no longer necessary with new opcode 319 for personal items that was introduced by EE at some date. The class choice for the NPC was introduced at a later stage on some user request.
If in game already, you just can remove the usability restriction (e.g. with NI) and the item should still be only usable by Sandrah.

Updated in mod itself already.
