### ISSUE TITLE
Error installing [SandrahNPC Creatures and Items] [v2.07]

### ISSUE THREAD

**Issue by PixelsnPolygons** [RoxanneSHS/SandrahEET#89]
Hello Roxanne,

I am working on my first EET installation and while researching compatible mods I decided very early on that your Sandrah Saga had to be included in my epic playthrough.

Alas, I am running into an error installing the first episode of Sandrah's Saga, specifically the "Creatures and Items" component. The "EET Additions" component also failed to install, but it appears that is because "Creatures and Items" is a prerequisite component.

Here is the error from Setup-SandrahNPC.debug - I also attached both WeiDU logs for my EET installation.

Installing` [SandrahNPC Creatures and Items] [v2.07]
Copying and patching 1 file ...
[SandrahNPC\CRE/Sandrah.cre] loaded, 3364 bytes
ERROR: cannot convert %CVMystra% or %%CVMystra%% to an integer
ERROR: [SandrahNPC\CRE/Sandrah.cre] -> [override\Sandrah.cre] Patching Failed (COPY) (Not_found)
Stopping installation because of error.

ERROR Installing [SandrahNPC Creatures and Items], rolling back to previous state
Unable to Unlink [SandrahNPC/backup/5/OTHER.5]: Unix.Unix_error(1, "unlink", "SandrahNPC/backup/5/OTHER.5")
[SandrahNPC/backup/5/UNSETSTR.5] SET_STRING uninstall info not found
Will uninstall   0 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 5.
Uninstalled      0 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 5.
Unable to Unlink [SandrahNPC/backup/5/READLN.5]: Unix.Unix_error(20, "unlink", "SandrahNPC/backup/5/READLN.5")
Unable to Unlink [SandrahNPC/backup/5/READLN.5.TEXT]: Unix.Unix_error(20, "unlink", "SandrahNPC/backup/5/READLN.5.TEXT")

[Setup-SandrahNPC.log](https://github.com/user-attachments/files/15831374/Setup-SandrahNPC.log)
[WeiDU-BGEE.log](https://github.com/user-attachments/files/15831389/WeiDU-BGEE.log)
[WeiDU.log](https://github.com/user-attachments/files/15831391/WeiDU.log)

**Comment by RoxanneSHS** [comment]
The error comes from some mod installed previously called EEEX (whatever that may be). You can try to manually uninstall Sandrah mod completely and then re-install it manually component by component. Sometimes that helps. Make sure you are not using a protected directory for installation thus creating local problems.
Otherwise it always helps to use https://github.com/EE-Mod-Setup/EE-Mod-Setup for large installations.

**Comment by PixelsnPolygons** [comment]
Thank you for the lightning fast response! I'll try installing each component one at a time.

If that doesn't work, I'll try installing your "Creatures and Items" component before my other item mods, in case the global changes those mods make are causing a problem for items in your mods.

> EEEX (whatever that may be)

EEex is Bubb's mod that extends the technical possibilities of other EE mods, it is essentially the EE equivalent of ToBEx. Bubb's Spell Menu Extended and Morpheus' Skill & Abilities are examples of cool mods that require EEex to be installed and then the EE game needs to be launched with EEex's InfinityLoader.exe component (from the EE game's directory).

https://github.com/Bubb13/Bubbs-Spell-Menu-Extended
https://www.morpheus-mart.com/skills-and-abilities

**Comment by PixelsnPolygons** [comment]
I stumbled across Project Infinity before I found EE Mod Setup, but I'll give it a try for future playthroughs.

BTW, I really appreciate your tenacity in getting so many classic mods compatible with EE and EET. Do you know the status of IWD-in-EET? K4thos seemed like he was done with an initial release, but I can't find it anywhere.

It sounds like Tipun has something pretty close, but there is (was?) an issue wherein BG party members couldn't rejoin if they were swapped out - not ideal for my play style.

**Comment by RoxanneSHS** [comment]
That Tobex equivalent is not suitable for large installations....but that is just my personal opinion, so take it as that.

The aforementioned install tool has an option for IWD in EET and this works well, however due to size and copyright issues it requires some manual action when preparing the installation - this is described in the pdf manual that comes with the tool download. Note that I only cover IWD1 and HoW with that. The status of IWD2 is unknown.

**Comment by PixelsnPolygons** [comment]
I am going to restart my EET installation without EEex. Few of the mods I have my heart set upon require its use, and those that do only require it for specific components. I will miss Morpheus' very cool Skill & Abilities casting concentration and spell penetration components.

In the process of acquainting myself with EE Mod Setup. I wish I discovered it before Project Infinity - it would have saved me so much time. It is clearly a more mature project. The included compilations are such a nice convenience and excellent teaching aid, whilst the installation order files are so much more efficient.

Project Infinity Unfinished Business for BGEE:
bg1ub:0;BG1 Unfinished Business - Ice Island Level Two Restoration
bg1ub:11;BG1 Unfinished Business - Scar and the Sashenstar's Daughter
bg1ub:12;BG1 Unfinished Business - Quoningar, the Cleric
bg1ub:13;BG1 Unfinished Business - Shilo Chen and the Ogre-Magi
bg1ub:14;BG1 Unfinished Business - Edie, the Merchant League Applicant
bg1ub:16;BG1 Unfinished Business - Creature Corrections
bg1ub:17;BG1 Unfinished Business - Creature Restorations
bg1ub:18;BG1 Unfinished Business - Creature Name Restorations
bg1ub:19;BG1 Unfinished Business - Minor Dialogue Restorations
bg1ub:22;BG1 Unfinished Business - Item Corrections and Restorations
bg1ub:29;BG1 Unfinished Business - Duke Eltan in the Harbor Master's Building
bg1ub:33;BG1 Unfinished Business - Mal-Kalen, the Ulcaster Ghost
bg1ub:34;BG1 Unfinished Business - Chapter 6 Dialogue Restorations

vs.

EE Mod Setup for Unfinished Business in BGEE:
bg1ub=0 11 12 13 14 16 17 18 19 21 22 29 33
