### ISSUE TITLE
Possible incorrect talk in simesannpcbant.tra file.

### ISSUE THREAD

**Issue by abalabokhin** [RoxanneSHS/SandrahEET#9]
In file "simesannpcbant.tra", Sime is addressed multiple times as a ranger (and a cleric of Mielikki). As far as I googled, Sime is a thief, but I didn't try to install the Sime mode. Is there an alternative Sime that can be a ranger?

**Comment by RoxanneSHS** [comment]
I suggest that you skip this mod. It is not the EET Sime mod (my own work) that extends the thief from Brynnlaw.

This crossmod was for old BGT which had a Sime mod where she was Aran's daughter and a ranger....this mod does not exist for EE.
`
ACTION_IF FILE_EXISTS_IN_GAME ~Sime110.cre~ THEN BEGIN`

**Comment by abalabokhin** [comment]
Ok, thank you.
