### ISSUE TITLE
If you finish HOW first (via Harbor master) and then go to IWD via Ulgoth's Beard, you are immediately teleprots back to Ulgoth's Beard as if IWD is already finished.

### ISSUE THREAD

**Issue by abalabokhin** [RoxanneSHS/SandrahEET#90]
p_zombie suggested to add this block to fix the issue:
```
IF
!Global("IWD1NOTCOMPLETE","Global",1)
!Global("SHERRY_PLOT","GLOBAL",81)
Global("SanHOWScar","Global",3)
Global("ERASE_IWD_JOURNAL","MYAREA",1)
InParty("CVSandr")
Global("GAME_OVER","MYAREA",0)
THEN
RESPONSE #100
SetGlobal("IWD1NOTCOMPLETE","Global",1)
SetGlobal("IWDEET_COMPLETE","GLOBAL",0)
END
```

to id9603howend.baf, but he is not sure and ask you to verify it if you can.

**Comment by RoxanneSHS** [comment]
What is Global("SHERRY_PLOT","GLOBAL",81) referring to?

**Comment by p-zombie2** [comment]
Hi Roxanne. 
As far as I know, IDTOEET1.baf is the final script in IWD1EET (included in icewind_eet mod), when the party returns back to Ulgoth's Beard, in which SetGlobal("SHERRY_PLOT","GLOBAL",81)
is set at the end (this is IDTOEET1.baf) :

IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(1)
		LeaveAreaLUAPanic("FC0125","",[687.665],14)
		LeaveAreaLUA("FC0125","",[687.665],14)
		ActionOverride(Player2,LeaveAreaLUA("FC0125","",[803.892],6))
		ActionOverride(Player3,LeaveAreaLUA("FC0125","",[575.742],12))
		ActionOverride(Player4,LeaveAreaLUA("FC0125","",[893.811],4))
		ActionOverride(Player5,LeaveAreaLUA("FC0125","",[798.675],2))
		ActionOverride(Player6,LeaveAreaLUA("FC0125","",[675.893],10))
		SetGlobal("PARTY_IN_ICEWIND_DALE","GLOBAL",0)
		Wait(1)
		SetSequence(SEQ_SLEEP)
		ActionOverride(Player2,SetSequence(SEQ_SLEEP))
		ActionOverride(Player3,SetSequence(SEQ_SLEEP))
		ActionOverride(Player4,SetSequence(SEQ_SLEEP))
		ActionOverride(Player5,SetSequence(SEQ_SLEEP))
		ActionOverride(Player6,SetSequence(SEQ_SLEEP))
		MoveGlobal("FC0125","fcsherri",[737.773])
		ActionOverride("fcsherri",FaceObject(Player1))
		Wait(1)
		FadeFromColor([15.0],0)
		Wait(1)
		MoveContainerContents("BG0125*IdImportContainer","FC0125*IdImportContainer")
		Wait(2)
		SetSequence(SEQ_AWAKE)
		ActionOverride(Player2,SetSequence(SEQ_AWAKE))
		ActionOverride(Player3,SetSequence(SEQ_AWAKE))
		ActionOverride(Player4,SetSequence(SEQ_AWAKE))
		ActionOverride(Player5,SetSequence(SEQ_AWAKE))
		ActionOverride(Player6,SetSequence(SEQ_AWAKE))
		Wait(1)
		SetGlobal("SHERRY_PLOT","GLOBAL",81)
		EndCutSceneMode()
		//SetCutSceneLite(TRUE)
		ActionOverride("fcsherri",StartDialogNoSet(Player1))
END

As far as I understand, this variable may be used as an indicator of whether IWD1EET was completed or not. More precisely Tipun could say, as the author of IWD1EET, but he rarely appears lately, he is in the hospital. 
In this case, perhaps there is a more correct way to determine whether HoW was completed first, or whether the main IWD1, to set SetGlobal("IWDEET_COMPLETE","GLOBAL",0) to correctly start the rest part.

**Comment by RoxanneSHS** [comment]
Thanks...
I consider this solution (to be independent from other mods and their globals as far as possible)

Add to bg0702.bcs (BG Harbourmaster area) 

IF
!Global("IWD1NOTCOMPLETE","bg0702",1)
!Global("SanIDW1","Global",27)  //Set if Sandrah was in IWD1 final fight
Global("SanHOWScar","Global",3) //Set if Sandrah was in HOW prior to IWD1
THEN
RESPONSE #100
SetGlobal("IWD1NOTCOMPLETE","bg0702",1)
SetGlobal("IWDEET_COMPLETE","GLOBAL",0)
END

I will test this in my current game in the next weeks because I have received Scar's mission recently but not been to IWD1 yet - so it fits into my playthrough. (PS - I have not encountered the problem before even though I played that sequence in this order before...)

**Comment by p-zombie2** [comment]
Thanks!
