### ISSUE TITLE
Many bags you can buy from woman in Beregost are the same bugs.

### ISSUE THREAD

**Issue by abalabokhin** [RoxanneSHS/SandrahEET#92]
There is woman in Beregost that sells different bags (eg bag for gems, etc). Without Sandrah mod she selling one type of every container that works, but with Sandrah mod installed, she sells many version of bags (eg 3 bags for gems) that are actually the same bags  (if you put something into one of them, it appears in another one). I am not sure it is a Sandrah mod bug (maybe the mod that adds this woman was updated and doesn't work properly), but the person, who reported about the bug believe that without Sandrah mod installed there only one version of every bag and everything works ok. Is it possible to check this issue?

**Comment by RoxanneSHS** [comment]
The woman is not added by Sandrah mod nor does that mod add something to another mod's merchant. In fact, the woman does not even exist in any of my installations, so I cannot check it. For further investigation, a name or creature reference would be helpful - otherwise it is chasing ghosts.

**Comment by abalabokhin** [comment]
Yes, sorry, it is Dark Horizons mod, closing the issue.
