### ISSUE TITLE
Strange problem, Sandrah's PIDs triggers fine in BG1, but not in SOD!

### ISSUE THREAD

**Issue by LeonZhao0215** [RoxanneSHS/SandrahEET#95]
Hello Roxanne, Thank you for your long term contribution!

I'm having a strange problem: Sandrah's PIDs are all right in BG1, and I believe I've completed all of Sandrah's quests as well. But once in SOD, Sandrah's interactions with other characters still work fine, such as Tamoko, but Sandrah's own PIDs don't trigger. Or should I say it's not 100%, but 99% of the time, in the Bhaal/Cyric temple, the encounter with the mindflayer triggers Sandrah's dialog, mentioning that it's pretty much the same as what happened with the Balduran's Seatower. But anything beyond that seems to be untriggered, such as Gorion's dagger.

I checked out this old thread
http://www.shsforums.net/topic/59011-sandrah-saga-for-eet-bug-and-support-forum/page-19
I don't have “Global(”EndofBG1“, ‘GLOBAL’,2)” inside my CVSandrJ.dlg file, 
but it does have“GlobalLT(“CHAPTER”, “GLOBAL”,20)” 
I deleted the latter, but it didn't change anything (I edited the CVSandrJ.dlg in the override folder, which is the correct path, right?)

After that I also tried running the “SandrahEET_PID_Repair” that you provided in that old thread, but it still didn't work. My method was to re-read the last save of BG1 and go into SOD again. After Imoen is attacked and poisoned by assassins, Sandrah is supposed to have a conversation with the duchess, but it doesn't trigger.

After trying all this, I'm afraid I can't solve this problem myself, so I had to come here to ask for help!

Thank you very much!

**Comment by RoxanneSHS** [comment]
I am not sure that I understand the problem...

PID means Player Initiated Dialogue, i.e. when you use your main character and the talk function to initiate talk with a party member. It only works, if you player character is in the first party slot (if you chose someone else, it will not work with Sandrah).
All other dialogue triggers in SoD are depending on situations and party constellations. EndofBG1=2 is only used to check BG2.
The global SanPidPack should be 12 in SoD.

**Comment by LeonZhao0215** [comment]
Thanks! Ok, it seems I used the term PIDs incorrectly. But the actual situation is that in BG1, everything about Sandrah was normal. After entering SOD, Sandrah basically stopped speaking actively, and important plots were no longer triggered (whether it was about Gorion's dagger in the temple, or Charname falling on the bridge).

Sorry, I'm a rookie, I used to rely on your forum for information. What is the command to check “Global SanPidPack”? If the value is lower than 12, will I fix the problem by setting it to 12? What is the command to set it?

Thank you very much!

<img width="1352" alt="SanPidPack" src="https://github.com/user-attachments/assets/ae4cc36b-aa7a-4acd-8f4d-71fcea8340a0">

**Comment by RoxanneSHS** [comment]
From your screenshot it appears that PID is correctly installed in the dialogue file. C:GetGlobal("Sanpidpack","Global") should give the current value.
It is possible that some parts of the mod concerning SoD were not installed...maybe you can check with NearInfinity as above by doing a search on scripts for   ("SanSodQuest","Global"     and see if it exists in some files

**Comment by LeonZhao0215** [comment]
I ran C:GetGlobal(“Sanpidpack”, “Global”).
It does show a value of 12

Unfortunately, when I search for SanSodQuest in "CVSandrJ.dlg" or "all dlg files", it says “No hits found”...

**Comment by RoxanneSHS** [comment]
If those triggers cannot be found, it indicates that parts of the mod have not been installed at all. You can check your weidu.log or the install logs (e.g. the file in EE-Debug.7z) for hints about what went wrong.
Unfortunately I have quit modding some time ago and forgot most about the details of how such a failure may (or may not) be corrected in an ongoing EET-game, so I have no advice for you here other than that the installation is incomplete. I cannot say which impact it has on the further game if you keep Sandrah in company (you can try - worst thing may be that she leaves party at some point).

**Comment by LeonZhao0215** [comment]
I think it's really the installation that's causing the problem. I used that auto-install tool that used to be on your forum, but since the forum is no longer there, I'm not sure if the install tool I downloaded was the latest version. The installation did report an error, but I kept trying to repeat the installation and the progress continued. After the installation is complete and I enter the game, the game will say that the installation is not complete. I forced the game to proceed because I found everything to be fine with Sandrah, so I continued until I got to the SOD.

Thank you very much, I think I'll try to do it all over again

**Comment by LeonZhao0215** [comment]
I've never installed EET manually before, any recommended tutorials? Should I install the Sandrah series last

Thank you very much！

**Comment by RoxanneSHS** [comment]
You could use some existing EET  weidu.log (and WeiDU-BGEE.log for mods that need to be installed on BGEE prior to running EET in BG2EE) that you have to get an idea about sequence. Sandrah goes towards the end but EET-End and the Worldmap mod need to go still after her.

**Comment by LeonZhao0215** [comment]
Although you have quit modding some time ago, you are still helping people. Once again, a sincere thank you!
