### ISSUE TITLE
When SandrahEET proceeds to the installation of “Mod interactions”, it reports an error

### ISSUE THREAD

**Issue by LeonZhao0215** [RoxanneSHS/SandrahEET#97]
Hi Roxanne
Thank you for your patience the other day!

I tried to do a manual install. I checked your readme about SandrahEET and pre-installed the required mods. However, when SandrahEET proceeds to the installation of “Mod interactions”, it reports an error. Please take a look, thank you very much!

Install Component [Mod Interactions]?
[I]nstall, or [N]ot Install or [Q]uit? i

Installing [Mod Interactions] [v2.07]
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Compiling 1 dialogue file ...
Extending game scripts ...
Compiling 1 dialogue file ...
Copying and patching 1 file ...
Compiling 1 script ...
Compiling 1 dialogue file ...

Fallen Paladin mod extended
Copying and patching 1 file ...
Copying 1 file ...
Copying and patching 1 file ...
Extending game scripts ...
Compiling 1 dialogue file ...
Compiling 1 dialogue file ...
Extending game scripts ...
Extending game scripts ...
Extending game scripts ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Extending game scripts ...
Compiling 1 dialogue file ...
Compiling 1 script ...

 Sandrah NTotSC part added

 Gavin not detected - Sandrah part skipped
Compiling 1 dialogue file ...
Compiling 1 dialogue file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Compiling 1 dialogue file ...
Compiling 1 script ...
Compiling 1 dialogue file ...
Extending game scripts ...

 BGQE Quest pack detected - Dauros demon hunt added
Compiling 1 dialogue file ...
Compiling 1 dialogue file ...
Extending game scripts ...

Perwell Quest detected - Sandrah Pelligram added
Extending game scripts ...
Compiling 1 dialogue file ...

 Stone of Askavar not detected - Sandrah part skipped

 Indira not detected - skipped

 Mur'Neth mod not detected - skipped
Compiling 1 dialogue file ...
Extending game scripts ...
Extending game scripts ...
Copying and patching 1 file ...
Copying and patching 1 file ...

 Dark Horizons detected - Sandrah add-on installed

Bone Hill not detected - skipped Sandrah add-on
Compiling 1 dialogue file ...
WARNING: internal label [6] not found in processed DLG [BRAN]
ERROR: processing .D actions [SandrahNPC/Mods/Sanvault.d]: Invalid_argument("index out of bounds")
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Mod Interactions], rolling back to previous state
Will uninstall  50 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 12.
Uninstalled     50 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 12.
ERROR: Invalid_argument("index out of bounds")
Please make a backup of the file: SETUP-SANDRAHNPC.DEBUG and look for support at: Roxanne - https://github.com/RoxanneSHS
Using Language [English]

Install Component [Mod Interactions]?
[I]nstall, or [N]ot Install or [Q]uit?

**Comment by LeonZhao0215** [comment]
[BRAN.dlg.txt](https://github.com/user-attachments/files/16715015/BRAN.dlg.txt)

This “BRAN”, is it “Branwen”?

**Comment by RoxanneSHS** [comment]
It is not Branwen but the priest Bran in the vestibule near the temple of Morninglord at Beregost.
Internal label 6 should be there if Vault mod is installed.
You can work around it by doing this:
Open the file SandrahNPC/Mods/SanVault.d with some text editor. Go to the very end of the file and look for
ADD_STATE_TRIGGER Bran 6 etc

Delete that line and all the remaining lines from the file. Then try again. (All that will be lost is some interaction between Sandrah and Edwin for the rare case that both are in party at that part of the vault quest - rather cosmetic and no real loss...)

**Comment by LeonZhao0215** [comment]
Thank you very much!

Mod interactions was successfully installed and advanced to the Sandrah RTF transition, but the final step, Sandrah additions, gave another error

Copying and patching 1 file ...

Black Pits access from Waterdeep added

IWD not detected - skipped

Better Pathfinding
Copying and patching 1 file ...
ERROR: error loading [C:\Users\songy\OneDrive\ĵ\Baldur's Gate - Enhanced Edition Trilogy/Baldur.lua]
Stopping installation because of error. “Baldur.lua” this time.

The lua file is indeed in the specified location, but the entire contents of the “Baldur's Gate - Enhanced Edition Trilogy” folder should be generated from my last playthrough. Is this related?
[Baldur.lua.txt](https://github.com/user-attachments/files/16721117/Baldur.lua.txt)



ERROR Installing [Sandrah EET additions], rolling back to previous state
Will uninstall 247 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 16.
Uninstalled    247 files for [SANDRAHNPC/SETUP-SANDRAHNPC.TP2] component 16.
ERROR: Unix.Unix_error(20, "stat", "C:\\Users\\songy\\OneDrive\\\206\196\181\181\\Baldur's Gate - Enhanced Edition Trilogy/Baldur.lua")
Please make a backup of the file: SETUP-SANDRAHNPC.DEBUG and look for support at: Roxanne - https://github.com/RoxanneSHS
Using Language [English]

**Comment by RoxanneSHS** [comment]
Do this:
Open the lua file and look for this line
SetPrivateProfileString('Program Options','Path Search Nodes','32000') and change the last value to 400000

Open the Setup-SandrahNPC.tp2 file from the mod folder with a text editor and go to the very end to find

PRINT ~Better Pathfinding~
Delete that whole block until the end of the file.

I have no idea why your installation uses OneDrive for EET but this seems not to be the place where Weidu finds the file...

**Comment by LeonZhao0215** [comment]
It worked! Thank you so much!!!

You know, no matter what those people say, for me, sandrah saga will always be my favorite. If it wasn't for Sandrah saga, I wouldn't even bother playing such an old game anymore. 

As for OneDrive, that's Microsoft's problem, it automatically appears inside the path of the document...

One more small problem, I have run eet end and completed the installation successfully. But after entering the game, the system still shows that the finalization was not completed and prompts to run eet end. this should just be an error message and have no real effect, right?

**Comment by RoxanneSHS** [comment]
You need EET-end to play the game. If it has been installed, then the message is an error and I think it is again an issue with the lua file because EET sets a status there.
Check in the lua
SetPrivateProfileString('Program Options','EET Installation State','2') 
if it is not 2 but you have EET end installed, then correct it. If the line is missing completely, then just add it. (Important: You must completely exit the game before you do changes in lua because otherwise it is overwritten when you next leave the game.)

**Comment by LeonZhao0215** [comment]
Resolved! Sincere thanks again!

I'm off to play~
