### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by southfla79** [RoxanneSHS/SandrahEET#99]
Not an issue, more of a question......what happened to the EE Mod Setup? My bookmark says it's gone. Was it moved to another user? If it's gone completely, what's your recommendation on a new install?

**Comment by RoxanneSHS** [comment]
Since I have lost my interest in modding the old game...it is no longer maintained. If you have an old version you can try how far it may take you, otherwise google for something else from the experts that have taken over.
